#!/usr/bin/env python
from Tkinter import *
import ttk

class Viewer:
    def __init__(self):
        self.window = None
        return
    
    def init_tree(self):
        self.window=Tk()
        self.tree = ttk.Treeview(self.window)
        self.tree["columns"]=("date","request")
        self.tree.column("#0",width=120)
        self.tree.column("date",width=190)
        self.tree.column("request",width=300)
        self.tree.heading("#0",text="IP")
        self.tree.heading("date",text="Date")
        self.tree.heading("request",text="Request")
        self.unique_id = 0
        self.id_map = {}

    def insert_line(self,line):
        if self.window:
            tokens = line.split()
            ip = tokens[0]
            timestamp = tokens[3]
            request = " ".join(tokens[5:])
            if timestamp[0] == '[':
                timestamp = timestamp[1:]
            if not ip in self.id_map:
                line_id = self.tree.insert("","end",self.unique_id,text=tokens[0])
                self.id_map[ip] = line_id
                self.unique_id += 1
            else:
                line_id = self.id_map[ip]
            self.tree.insert(line_id,"end",self.unique_id,values = [timestamp, request])
            self.unique_id += 1
        else:
            print(line)

    def show_dialog(self):
        if self.window:
            self.tree.tag_configure("ttk")
            self.tree.pack(side=TOP,fill=X)
            self.window.mainloop()


from sys import argv
from getopt import getopt,GetoptError

# Defaults
viewer = Viewer()
use_gui = True

try:
    (opts,args) = getopt(argv[1:],"",["cli"])
except GetoptError as ge:
    print(ge.msg)
    error_out(HELP_WARNING)

for (opt, optarg) in opts:
    while opt[0] == '-':
        opt = opt[1:]
    if opt == "cli":
        use_gui = False

if len(args) != 1:
    error_out(HELP_WARNING)

infilename = args[0]

if use_gui:
    viewer.init_tree()

if ".gz" in infilename:
    import gzip
    infile = gzip.open(infilename,"r")
else:
    infile = open(infilename,"r")

for line in infile:
    viewer.insert_line(line.strip())

viewer.show_dialog()
